# Generated by Django 5.0.6 on 2024-07-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('header_image', models.ImageField(upload_to='static/')),
                ('release_date', models.DateTimeField()),
                ('article_body', models.TextField(max_length=20000)),
            ],
        ),
    ]
