# Generated by Django 5.0.6 on 2024-08-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articles_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
