# Generated by Django 5.0.6 on 2024-06-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_img', models.ImageField(upload_to='')),
                ('skin_name', models.CharField(max_length=30, unique=True)),
                ('release_date', models.DateTimeField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
