# Generated by Django 5.0.6 on 2024-06-30 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comments_owner_id_comments_skin'),
        ('skin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skins',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.comments'),
        ),
    ]
