# Generated by Django 5.0.6 on 2024-07-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0002_skins_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skins',
            name='skin_img',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
