# Generated by Django 5.0.6 on 2024-09-05 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_rename_skin_comments_skin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='skin_id',
            new_name='skin',
        ),
    ]
